server:
  port: 8080

spring:
  application:
    name: spring-boot-tutorial
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tvseries?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: root
  jackson:
    serialization:
      write-dates-as-timestamps: true  #使用数值timestamp表示日期

mybatis.configuration.mapUnderscoreToCamelCase: true

logging:
  file: target/app.log
  level:
    ROOT: WARN
    cn.devmgr: TRACE
    cn.devmgr.tutorial.dao: WARN

#此项目的自定义属性  
tutorial:
  uploadFolder: target/upload-files/    #文件上传目录，可以用/开头的绝对路径
     